
server:
  port: 9001

spring:
  application:
    name: practice-exam

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/practice_exam?characterEncoding=utf-8&useUnicode=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: practice_exam
      connection-timeout: 60000
      maximum-pool-size: 10
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true

snowflake:
  data-center-id: 0
  worker-id: 2

jwt:
  secretKey: practice123exam

# 阿里对象存储
alioss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4Fh9ekeoPC5nS2x4mRvN
  accessKeySecret: b7T1y9S9KsAhMPL4jtlhCNnQyW99gS
  bucketName: farmeryun



